# Generated by Django 6.0.3 on 2026-03-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto_favor', models.PositiveIntegerField(default=0)),
                ('voto_contra', models.PositiveIntegerField(default=0)),
                ('abstencion', models.PositiveIntegerField(default=0)),
                ('favorable', models.BooleanField(default=False)),
                ('abierta', models.BooleanField(default=False)),
                ('apertura', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.DateTimeField(blank=True, null=True)),
                ('punto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='votacion', to='actas.ordendia')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('Favor', 'Favor'), ('Contra', 'Contra'), ('Abstencion', 'Abstencion')], default='Favor', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='usuarios.usuario')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='votos.votacion')),
            ],
            options={
                'unique_together': {('votacion', 'usuario')},
            },
        ),
    ]
