# Generated by Django 6.0.3 on 2026-03-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('proceso', 'proceso'), ('resuelta', 'resuelta')], default='proceso', max_length=10),
        ),
    ]
