# Generated by Django 6.0.3 on 2026-03-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_alter_incidencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('inicio', 'inicio'), ('proceso', 'proceso'), ('resuelta', 'resuelta')], default='inicio', max_length=10),
        ),
    ]
