# Generated by Django 6.0.3 on 2026-05-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad_info', '0008_alter_comunidad_options'),
        ('info', '0002_remove_informacion_usuarios'),
        ('usuarios', '0003_usuario_gestor_fincas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('incidencia', 'incidencia'), ('comunicado', 'comunicado'), ('acta', 'acta'), ('general', 'general')], default='general', max_length=50)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad_info.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='AvisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default=False)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_usuario', to='info.aviso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_usuario', to='usuarios.usuario')),
            ],
        ),
    ]
