# Generated by Django 6.0.3 on 2026-05-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_aviso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('incidencia', 'incidencia'), ('convocatoria', 'convocatoria'), ('info', 'info'), ('acta', 'acta'), ('general', 'general')], default='general', max_length=50),
        ),
    ]
