# Generated by Django 6.0.3 on 2026-05-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_aviso_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='id_elemento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
