# Generated by Django 6.0.3 on 2026-03-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidad_info', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('ordinaria', 'ordinaria'), ('extraordinaria', 'extraordinaria')], default='ordinaria', max_length=15)),
                ('convocatoria', models.CharField(choices=[('primera', 'primera'), ('segunda', 'segunda')], default='primera', max_length=15)),
                ('lugar', models.CharField(max_length=200)),
                ('resuelta', models.BooleanField(default=False)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='comunidad_info.comunidad')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_creadas', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('representante', models.CharField(blank=True, max_length=200, null=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='actas.acta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='acta',
            name='usuarios',
            field=models.ManyToManyField(related_name='actas', through='actas.Asistencia', to='usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='OrdenDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=1000)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='actas.acta')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
