# Generated by Django 6.0.3 on 2026-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
