# Generated by Django 6.0.3 on 2026-04-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_alter_acta_fecha'),
        ('comunidad_info', '0007_propiedad_propiedad_unica_en_la_comunidad'),
        ('usuarios', '0002_remove_usuario_moroso_remove_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acta',
            options={},
        ),
        migrations.RemoveField(
            model_name='acta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='titulo',
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('ordinaria', 'ordinaria'), ('extraordinaria', 'extraordinaria')], default='ordinaria', max_length=15)),
                ('lugar', models.CharField(max_length=200)),
                ('celebrada', models.BooleanField(default=False)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias', to='comunidad_info.comunidad')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocatorias_creadas', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='acta',
            name='convocatoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actas_convocatoria', to='actas.convocatoria'),
        ),
    ]
