# Generated by Django 6.0.3 on 2026-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0003_alter_acta_options_remove_acta_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
