# Generated by Django 6.0.3 on 2026-04-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0004_convocatoria_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='num_convocatoria',
            field=models.CharField(choices=[('primera', 'primera'), ('segunda', 'segunda')], default='primera', max_length=15),
        ),
    ]
