# Generated by Django 6.0.3 on 2026-04-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0005_convocatoria_num_convocatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendia',
            name='convocatoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='actas.convocatoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordendia',
            name='acta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos', to='actas.acta'),
        ),
    ]
