# Generated by Django 6.0.3 on 2026-04-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0006_ordendia_convocatoria_alter_ordendia_acta'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='fecha_fin',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
