# Generated by Django 6.0.3 on 2026-04-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0007_acta_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
