# Generated by Django 6.0.3 on 2026-04-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0008_alter_acta_fecha_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acta',
            old_name='fecha_fin',
            new_name='timestamp_fin',
        ),
    ]
