# Generated by Django 6.0.3 on 2026-04-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0009_rename_fecha_fin_acta_timestamp_fin'),
        ('usuarios', '0002_remove_usuario_moroso_remove_usuario_rol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('acta', 'usuario')},
        ),
    ]
