# Generated by Django 6.0.3 on 2026-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0010_alter_asistencia_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='resumen',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='timestamp_inicio',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
