# Generated by Django 6.0.3 on 2026-04-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0012_alter_acta_timestamp_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='timestamp_inicio',
        ),
    ]
