# Generated by Django 6.0.3 on 2026-04-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0013_remove_acta_timestamp_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='timestamp_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
