# Generated by Django 6.0.3 on 2026-04-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0014_acta_timestamp_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='convocatoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_convocatoria', to='actas.convocatoria'),
        ),
    ]
