# Generated by Django 6.0.3 on 2026-05-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0015_alter_acta_convocatoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'ordering': ['-fecha', '-hora']},
        ),
    ]
