# Generated by Django 6.0.3 on 2026-05-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0016_alter_convocatoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acta',
            options={'ordering': ['-timestamp_inicio']},
        ),
    ]
