# Generated by Django 6.0.3 on 2026-06-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0017_alter_acta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'ordering': ['-pk']},
        ),
    ]
