# Generated by Django 6.0.3 on 2026-06-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0018_alter_convocatoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'ordering': ['-fecha', '-hora']},
        ),
    ]
