# Generated by Django 6.0.3 on 2026-03-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidad_info', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='comunidad_info.comunidad')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creador_comunicado', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComunicadoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicado_usuario', to='comunicados.comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicado_usuario', to='usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comunicado',
            name='usuarios',
            field=models.ManyToManyField(related_name='comunicados', through='comunicados.ComunicadoUsuario', to='usuarios.usuario'),
        ),
    ]
