# Generated by Django 6.0.3 on 2026-04-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicadousuario',
            options={'ordering': ['-comunicado__fecha_creacion']},
        ),
    ]
