# Generated by Django 6.0.3 on 2026-04-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0002_alter_comunicadousuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'ordering': ['-fecha_creacion'], 'permissions': (('gestor', 'EsGestor'),)},
        ),
    ]
