# Generated by Django 6.0.3 on 2026-05-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0003_alter_comunicado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'ordering': ['-fecha_creacion'], 'permissions': (('gestor', 'EsGestor'), ('presidente', 'EsPresidente'))},
        ),
    ]
