# Generated by Django 6.0.3 on 2026-03-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cod_postal', models.CharField(max_length=5)),
                ('localidad', models.CharField(max_length=200)),
                ('provincia', models.CharField(blank=True, max_length=200, null=True)),
                ('cif', models.CharField(help_text='Código de identificación fiscal', max_length=9, unique=True)),
                ('gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidad', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_letra', models.CharField(max_length=5)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='comunidad_info.comunidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='usuarios.usuario')),
            ],
        ),
    ]
