# Generated by Django 6.0.3 on 2026-04-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad_info', '0001_initial'),
        ('usuarios', '0002_remove_usuario_moroso_remove_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='gestor',
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='comunidad_info.comunidad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='RolComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('gestor', 'gestor'), ('presidente', 'presidente'), ('propietario', 'propietario'), ('vicepresidente', 'vicepresidente'), ('secretario', 'secretario')], default='propietario', max_length=30)),
                ('moroso', models.BooleanField(default=False)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='comunidad_info.comunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comunidad',
            name='usuarios',
            field=models.ManyToManyField(related_name='comunidades', through='comunidad_info.RolComunidad', to='usuarios.usuario'),
        ),
    ]
