# Generated by Django 6.0.3 on 2026-04-01 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad_info', '0002_remove_comunidad_gestor_alter_propiedad_comunidad_and_more'),
        ('usuarios', '0002_remove_usuario_moroso_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunidad', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='rolcomunidad',
            name='rol',
            field=models.CharField(choices=[('presidente', 'presidente'), ('propietario', 'propietario'), ('vicepresidente', 'vicepresidente'), ('secretario', 'secretario')], default='propietario', max_length=30),
        ),
    ]
