# Generated by Django 6.0.3 on 2026-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad_info', '0003_comunidad_gestor_alter_rolcomunidad_rol'),
        ('usuarios', '0002_remove_usuario_moroso_remove_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='gestor',
        ),
        migrations.AlterField(
            model_name='rolcomunidad',
            name='rol',
            field=models.CharField(choices=[('gestor', 'gestor'), ('presidente', 'presidente'), ('propietario', 'propietario'), ('vicepresidente', 'vicepresidente'), ('secretario', 'secretario')], default='propietario', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='rolcomunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'gestor')), fields=('comunidad',), name='unico_gestor_por_comunidad'),
        ),
        migrations.AddConstraint(
            model_name='rolcomunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'presidente')), fields=('comunidad',), name='unico_presidente_por_comunidad'),
        ),
        migrations.AddConstraint(
            model_name='rolcomunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'vicepresidente')), fields=('comunidad',), name='unico_vicepresidente_por_comunidad'),
        ),
        migrations.AddConstraint(
            model_name='rolcomunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'secretario')), fields=('comunidad',), name='unico_secretario_por_comunidad'),
        ),
    ]
