# Generated by Django 6.0.3 on 2026-04-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad_info', '0004_remove_comunidad_gestor_alter_rolcomunidad_rol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolcomunidad',
            options={'ordering': ['comunidad__nombre']},
        ),
    ]
