# Generated by Django 6.0.3 on 2026-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad_info', '0005_alter_rolcomunidad_options'),
        ('usuarios', '0002_remove_usuario_moroso_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rolcomunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('rol__in', ['presidente', 'vicepresidente', 'secretario', 'propietario'])), fields=('usuario', 'comunidad'), name='un_solo_rol_por_usuario_comunidad'),
        ),
    ]
