# Generated by Django 6.0.3 on 2026-04-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad_info', '0006_rolcomunidad_un_solo_rol_por_usuario_comunidad'),
        ('usuarios', '0002_remove_usuario_moroso_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='propiedad',
            constraint=models.UniqueConstraint(fields=('num_letra', 'comunidad'), name='propiedad_unica_en_la_comunidad'),
        ),
    ]
