# Generated by Django 6.0.3 on 2026-05-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad_info', '0007_propiedad_propiedad_unica_en_la_comunidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunidad',
            options={'ordering': ['nombre']},
        ),
    ]
