# Generated by Django 6.0.3 on 2026-05-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad_info', '0008_alter_comunidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='num_letra',
            field=models.CharField(max_length=10),
        ),
    ]
