# Generated by Django 6.0.3 on 2026-03-19 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido1', models.CharField(max_length=200)),
                ('apellido2', models.CharField(blank=True, max_length=200, null=True)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('rol', models.CharField(choices=[('gestor', 'gestor'), ('presidente', 'presidente'), ('propietario', 'propietario'), ('vicepresidente', 'vicepresidente'), ('secretario', 'secretario')], default='propietario', max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('moroso', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
