# Generated by Django 6.0.3 on 2026-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_moroso_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gestor_fincas',
            field=models.BooleanField(default=False),
        ),
    ]
